[package]
name = "xcx_archive_tools"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
xcx_archive = { path = "./xcx_archive" }

[workspace]
members = [
  "read_binary", "xcx_archive",
]
